Failed experiment to use custom tree nodes for docstrings.
Fails with
```
X org.scalafmt.tests.DocstringSuite.docstring is printed 20ms
  java.lang.ClassCastException: scala.meta.internal.format.CustomTrees$Docstring cannot be cast to s
  cala.meta.Defn$Def
    scala.meta.Defn$Def$DefnDefImpl.privateCopy(Trees.scala:269)
    scala.meta.internal.format.CustomTrees$Docstring.privateCopy(CustomTrees.scala:60)
    scala.meta.Template$.$anonfun$apply$112(Trees.scala:346)
    scala.collection.immutable.List.map(List.scala:283)
```

Seems this approach is a dead end due to implementation details of
scala.meta.Tree. It's not a perfect solution either, since it would mean
all transforms/traverses would have to take docstring tree nodes into
account. It was worth a shot.